name: Justin Alm
description: I am a user experience and user interface designer living in Vancouver, Canada. I live in the world of product strategy, information architecture, and visual design. I care about how things work as much how good things feel. I work at Steamclock Software.
url: http://justinalm.com
pygments: true
permalink: none
paginate: 5