name: Justin Alm
description: I am a user experience and user interface designer from Vancouver, Canada. I live in the world of product strategy, information architecture, and visual design.
url: http://justinalm.com
pygments: true
permalink: none
paginate: 5